nginx-proxy:
  image: jwilder/nginx-proxy
  restart: always
  ports:
    - "80:80"
    - "8080:8080"
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock:ro

index:
  image: nginx
  restart: always
  expose:
    - "80"
  volumes:
    - ~/src/index.html:/usr/share/nginx/html/index.html:rw
  environment:
    - VIRTUAL_HOST=test.com

ping:
  image: ping
  restart: always
  expose:
    - "8080"
  environment:
    - VIRTUAL_HOST=ping.com
