apiVersion: apps/v1 
kind: Deployment 
metadata:
  name: ping
spec:
  replicas: 3
  selector:
    matchLabels:
      role: ping
  template:
    metadata:
      labels:
        role: ping
    spec:
      containers:
      - name: ping
        image: adsprogramer/isai
        imagePullPolicy: IfNotPresent        
        ports:
        - containerPort: 8080
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "password"
        resources:
          requests:
            memory: "64Mi"
            cpu: "200m"
          limits:
            memory: "128Mi"
            cpu: "500m"
