on: push
name: deploy
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master
      name: build and push to docker
    - uses: docker/build-push-action@v2.2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: ${{ github.repository }}
        tag_with_ref: true
        tag_with_sha: true
        tags: ${{ github.sha }}
